services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    environment:
      - ISC_CPF_MERGE_FILE=/home/irisowner/dev/merge.cpf
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: --check-caps false --ISCAgent false
    ports:
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
